version: '3.8'

services:
  # Servicio de Redis con módulos JSON y Search
  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6379:6379" # Puerto estándar de Redis
      - "8001:8001" # Puerto para la UI de RedisInsight 
    volumes:
      - redis_data:/data
    networks:
      - redis-net

  # Servicio de la aplicación Python
  python:
    container_name: python_app
    build:
      context: ./python-app  # Construye desde la carpeta ./python-app
    depends_on:
      - redis                 # Espera a que Redis esté listo
    environment:
      # Pasa el nombre del host de Redis al contenedor de Python
      - REDIS_HOST=redis
      # === NUEVAS VARIABLES PARA MYSQL ===
      - MYSQL_HOST=mysql # Nombre del contenedor MySQL
      - MYSQL_DB=centrocuidadofamiliar # DATABASE
      - MYSQL_USER=root 
      - MYSQL_PASSWORD=0853 
    networks:
      - redis-net
      - mysql-external-net # Nueva red para conectarse a MySQL
    volumes:
      # Monta la carpeta de la BD SQL en el contenedor
      - ./python-app/db:/app/db
    # Mantiene el contenedor corriendo para que podamos ejecutar scripts
    command: tail -f /dev/null

networks:
  redis-net:
    driver: bridge
  # === DECLARAMOS LA RED EXTERNA DE MYSQL ===
  mysql-external-net:
    external:
      name: multidatabase_default

volumes:
  redis_data: