services:
  # Servicio de Redis con módulos JSON y Search
  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    ports:
      - "6379:6379" # Puerto estándar de Redis
      - "8001:8001" # Puerto para la UI de RedisInsight 
    volumes:
      - redis_data:/data
    networks:
      - redis-net

  # Servicio de la aplicación Python
  python:
    container_name: python_app
    build:
      context: ./python-app  # Construye desde la carpeta ./python-app
    depends_on:
      - redis                  # Espera a que Redis esté listo
    environment:
      # Pasa el nombre del host de Redis al contenedor de Python
      - REDIS_HOST=redis
      # === VARIABLES PARA MYSQL ===
      - MYSQL_HOST=mysql # Nombre del contenedor MySQL
      - MYSQL_DB=CENTROCUIDADOFAMILIAR # DATABASE
      - MYSQL_USER=root 
      - MYSQL_PASSWORD=0853 
    networks:
      - redis-net
      - mysql-external-net # Nueva red para conectarse a MySQL
    volumes:
      - ./python-app:/app
    command: sleep 3600

networks:
  redis-net:
    driver: bridge
  # === RED EXTERNA DE MYSQL (Sintaxis moderna) ===
  mysql-external-net:
    name: multidatabase_default # Este es el nombre de tu red de MySQL
    external: true

volumes:
  redis_data: